---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: database
spec:
  containers:
    - name: mysql
      imagePullPolicy: Always
      image: padmaravi/mysql:robo
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    name: mysql
    tier: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
