---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  MYSQL_DATABASE: cities
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: c2VjcmV0

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: database
spec:
  containers:
    - name: mysql
      imagePullPolicy: Always
      image: padmaravi/mysql:robo
      envFrom:
      - configMapRef:
         name: mysql-config
      - secretRef:
         name: mysql-secrets
      ports:
       - containerPort: 3306
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    name: mysql
    tier: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3306
