---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    tier: database
spec:
  containers:
    - name: redis
      imagePullPolicy: Always
      image: redis
      ports:
       - containerPort: 6379
      resources:
        requests:
          cpu: "200m"
          memory: "328Mi"
        limits:
          cpu: "200m"
          memory: "328Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
    tier: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
---