---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    name: mongodb
    tier: database
spec:
  containers:
    - name: mongo
      imagePullPolicy: Always
      image: padmaravi/mongo:newv3
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tier: database
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
