---
apiVersion: v1
kind: Pod
metadata:
  name: mangodb
  labels:
    name: mangodb
    tier: database
spec:
  containers:
    - name: mangodb
      imagePullPolicy: Always
      image: padmaravi/mongo:robo
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mangodb-service
spec:
  selector:
    name: mangodb
    tier: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
