# ---
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: cpu-mem-limit-range
# spec:
#   limits:
#    resources:
#     requests: 
#      memory: '64Mi'
#      cpu: '250m'
#     limits:
#      memory: '200Mi'
#      cpu: '500m'
#     type: Container
# ---
apiVersion: v1
kind: Pod
metadata:
 name: resource
spec:
 containers:
 - name: nginx
   image: nginx
   resources:
    requests: 
     memory: '64Mi'
     cpu: '250m'
    limits:
     memory: '200Mi'
     cpu: '500m'