---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limit-range
spec:
  limits:
  - max:
      cpu: "2"
      memory: 2Gi
    min:
      cpu: "200m"
      memory: 100Mi
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
 name: resource
spec:
 containers:
 - name: nginx
   image: nginx
  #  resources:
  #   requests: 
  #    memory: '64Mi'
  #    cpu: '250m'
  #   limits:
  #    memory: '200Mi'
  #    cpu: '500m'