apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: env-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: course
      value: "Hello from the Kubernates"
    - name: duration
      value: 25hr