--- # ---

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: env-config
#   labels:
#     purpose: demonstrate-envars
# spec:
#   containers:
#     - name: env-demo-container
#       image: gcr.io/google-samples/node-hello:1.0
#       env:
#         - name: course
#           valueFrom:
#             ConfigMapKeyRef:
#               name: kubernates-demo
#               key: course
#         - name: durarion
#           valueFrom:
#             ConfigMapKeyRef:
#               name: kubernates-demo
#               key: duration
apiVersion: v1 ## in real time we use like this only
kind: Pod
metadata:
  name: env-config
  labels:
    purpose: demonstrate-envars
spec:
  containers:
    - name: env-demo-container
      image: gcr.io/google-samples/node-hello:1.0
      envFrom:
        - ConfigMapRef:
            name: kubernates-demo
